import Head from 'next/head';
import Image from 'next/image';
import BlogPosts from '../components/BlogPosts';
import { Logo } from '../components/Logo';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page">
        <section className="intro">
          <Logo />

          <h1>Hello there!</h1>

          <p>
            This little project uses Next.js, with React and CSS along for the
            ride.
          </p>

          <p>Now, time for some blog articles.</p>
        </section>

        <BlogPosts data={[]} />
      </main>
    </div>
  );
}
